# Generated by Django 5.0.3 on 2024-04-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.AddField(
            model_name='article',
            name='article_img',
            field=models.ImageField(default=1, upload_to='articles'),
            preserve_default=False,
        ),
    ]
