# Generated by Django 5.0.3 on 2024-04-09 15:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='articles'),
        ),
    ]
