# Generated by Django 5.0.3 on 2024-03-09 14:58

import autovibe_project.cars.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('country_of_origin', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('logo', models.ImageField(upload_to='brand_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('year', models.PositiveIntegerField(validators=[autovibe_project.cars.validators.get_current_year_plus_one])),
                ('color', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.PositiveIntegerField()),
                ('vin', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='car_images/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carbrand')),
            ],
        ),
        migrations.CreateModel(
            name='CarFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interior_features', models.CharField(blank=True, choices=[('leather_seats', 'Leather Seats'), ('navigation_system', 'Navigation System'), ('heated_seats', 'Heated Seats'), ('sunroof', 'Sunroof'), ('power_windows', 'Power Windows'), ('power_seats', 'Power Seats'), ('memory_seats', 'Memory Seats'), ('climate_control', 'Climate Control'), ('premium_audio_system', 'Premium Audio System'), ('wireless_charging', 'Wireless Charging'), ('ambient_lighting', 'Ambient Lighting'), ('rear_entertainment_system', 'Rear Entertainment System')], max_length=100)),
                ('exterior_features', models.CharField(blank=True, choices=[('alloy_wheels', 'Alloy Wheels'), ('led_headlights', 'LED Headlights'), ('panoramic_roof', 'Panoramic Roof'), ('power_tailgate', 'Power Tailgate'), ('power_sliding_doors', 'Power Sliding Doors'), ('roof_rails', 'Roof Rails'), ('fog_lights', 'Fog Lights'), ('automatic_headlights', 'Automatic Headlights'), ('rain_sensing_wipers', 'Rain Sensing Wipers'), ('heated_mirrors', 'Heated Mirrors'), ('parking_sensors', 'Parking Sensors'), ('backup_camera', 'Backup Camera')], max_length=100)),
                ('safety_features', models.CharField(blank=True, choices=[('abs', 'ABS'), ('airbags', 'Airbags'), ('lane_departure_warning', 'Lane Departure Warning'), ('automatic_emergency_braking', 'Automatic Emergency Braking'), ('blind_spot_monitoring', 'Blind Spot Monitoring'), ('adaptive_cruise_control', 'Adaptive Cruise Control'), ('forward_collision_warning', 'Forward Collision Warning'), ('rear_cross_traffic_alert', 'Rear Cross Traffic Alert'), ('parking_assist', 'Parking Assist'), ('tire_pressure_monitoring', 'Tire Pressure Monitoring'), ('driver_assist_package', 'Driver Assist Package'), ('night_vision_assist', 'Night Vision Assist')], max_length=100)),
                ('other_features', models.TextField(blank=True, max_length=500)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
    ]
