# Generated by Django 5.0.3 on 2024-03-09 16:53

import autovibe_project.cars.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_telephone_number_and_more'),
        ('cars', '0002_carbrand_description_alter_carbrand_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarFeature',
            new_name='CarFeaturePost',
        ),
        migrations.CreateModel(
            name='CarPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('year', models.PositiveIntegerField(validators=[autovibe_project.cars.validators.get_current_year_plus_one])),
                ('color', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.PositiveIntegerField()),
                ('vin', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='car_images/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carbrand')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
        migrations.AlterField(
            model_name='carfeaturepost',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carpost'),
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
