# Generated by Django 5.0.3 on 2024-03-12 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_carpost_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpost',
            old_name='profile',
            new_name='user',
        ),
    ]
