# Generated by Django 5.0.3 on 2024-03-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_rename_profile_carpost_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carfeaturepost',
            name='car',
        ),
        migrations.AddField(
            model_name='carpost',
            name='features',
            field=models.ManyToManyField(blank=True, to='cars.carfeaturepost'),
        ),
    ]
