# Generated by Django 5.0.3 on 2024-03-13 10:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(choices=[('ACURA', 'ACURA'), ('ALFA ROMEO', 'ALFA ROMEO'), ('ASTON MARTIN', 'ASTON MARTIN'), ('AUDI', 'AUDI'), ('BENTLEY', 'BENTLEY'), ('BMW', 'BMW'), ('BUICK', 'BUICK'), ('CADILLAC', 'CADILLAC'), ('CHEVROLET', 'CHEVROLET'), ('CHRYSLER', 'CHRYSLER'), ('DODGE', 'DODGE'), ('FERRARI', 'FERRARI'), ('FIAT', 'FIAT'), ('FORD', 'FORD'), ('GENESIS', 'GENESIS'), ('GMC', 'GMC'), ('HONDA', 'HONDA'), ('HYUNDAI', 'HYUNDAI'), ('INFINITI', 'INFINITI'), ('JAGUAR', 'JAGUAR'), ('JEEP', 'JEEP'), ('KIA', 'KIA'), ('LAMBORGHINI', 'LAMBORGHINI'), ('LAND ROVER', 'LAND ROVER'), ('LEXUS', 'LEXUS'), ('LINCOLN', 'LINCOLN'), ('LOTUS', 'LOTUS'), ('MASERATI', 'MASERATI'), ('MAZDA', 'MAZDA'), ('MCLAREN', 'MCLAREN'), ('MERCEDES-BENZ', 'MERCEDES-BENZ'), ('MINI', 'MINI'), ('MITSUBISHI', 'MITSUBISHI'), ('NISSAN', 'NISSAN'), ('PAGANI', 'PAGANI'), ('PORSCHE', 'PORSCHE'), ('RAM', 'RAM'), ('ROLLS-ROYCE', 'ROLLS-ROYCE'), ('SMART', 'SMART'), ('SUBARU', 'SUBARU'), ('TESLA', 'TESLA'), ('TOYOTA', 'TOYOTA'), ('VOLKSWAGEN', 'VOLKSWAGEN'), ('VOLVO', 'VOLVO')], max_length=100)),
                ('logo', models.URLField(blank=True, max_length=220, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpost.carbrands')),
            ],
        ),
        migrations.CreateModel(
            name='CarPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('model', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)])),
                ('color', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=100)),
                ('petrol_type', models.CharField(max_length=100)),
                ('transmission', models.CharField(max_length=100)),
                ('chassis', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mileage', models.PositiveIntegerField()),
                ('vin', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='car_images/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpost.carbrands')),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpost.carmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interior_features', models.CharField(blank=True, choices=[('leather_seats', 'Leather Seats'), ('navigation_system', 'Navigation System'), ('heated_seats', 'Heated Seats'), ('sunroof', 'Sunroof'), ('power_windows', 'Power Windows'), ('power_seats', 'Power Seats'), ('memory_seats', 'Memory Seats'), ('climate_control', 'Climate Control'), ('premium_audio_system', 'Premium Audio System'), ('wireless_charging', 'Wireless Charging'), ('ambient_lighting', 'Ambient Lighting'), ('rear_entertainment_system', 'Rear Entertainment System')], max_length=100)),
                ('exterior_features', models.CharField(blank=True, choices=[('alloy_wheels', 'Alloy Wheels'), ('led_headlights', 'LED Headlights'), ('panoramic_roof', 'Panoramic Roof'), ('power_tailgate', 'Power Tailgate'), ('power_sliding_doors', 'Power Sliding Doors'), ('roof_rails', 'Roof Rails'), ('fog_lights', 'Fog Lights'), ('automatic_headlights', 'Automatic Headlights'), ('rain_sensing_wipers', 'Rain Sensing Wipers'), ('heated_mirrors', 'Heated Mirrors'), ('parking_sensors', 'Parking Sensors'), ('backup_camera', 'Backup Camera')], max_length=100)),
                ('safety_features', models.CharField(blank=True, choices=[('abs', 'ABS'), ('airbags', 'Airbags'), ('lane_departure_warning', 'Lane Departure Warning'), ('automatic_emergency_braking', 'Automatic Emergency Braking'), ('blind_spot_monitoring', 'Blind Spot Monitoring'), ('adaptive_cruise_control', 'Adaptive Cruise Control'), ('forward_collision_warning', 'Forward Collision Warning'), ('rear_cross_traffic_alert', 'Rear Cross Traffic Alert'), ('parking_assist', 'Parking Assist'), ('tire_pressure_monitoring', 'Tire Pressure Monitoring'), ('driver_assist_package', 'Driver Assist Package'), ('night_vision_assist', 'Night Vision Assist')], max_length=100)),
                ('other_features', models.TextField(blank=True, max_length=500)),
                ('car_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpost.carpost')),
            ],
        ),
    ]
