# Generated by Django 5.0.3 on 2024-03-13 11:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpost',
            old_name='brand',
            new_name='car_brand',
        ),
        migrations.RemoveField(
            model_name='carfeatures',
            name='car_post',
        ),
        migrations.RemoveField(
            model_name='carpost',
            name='model',
        ),
        migrations.AddField(
            model_name='carpost',
            name='car_feature',
            field=models.ManyToManyField(to='carpost.carfeatures'),
        ),
        migrations.AlterField(
            model_name='carpost',
            name='chassis',
            field=models.CharField(choices=[('2WD', '2WD'), ('4WD', '4WD'), ('AWD', 'AWD')], max_length=100),
        ),
        migrations.AlterField(
            model_name='carpost',
            name='color',
            field=models.CharField(choices=[('Red', 'Red'), ('Blue', 'Blue'), ('Black', 'Black'), ('White', 'White'), ('Silver', 'Silver'), ('Green', 'Green'), ('Yellow', 'Yellow'), ('Orange', 'Orange'), ('Purple', 'Purple'), ('Pink', 'Pink')], max_length=50),
        ),
        migrations.AlterField(
            model_name='carpost',
            name='engine',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=20),
        ),
        migrations.AlterField(
            model_name='carpost',
            name='municipality',
            field=models.CharField(choices=[('Blagoevgrad', 'Blagoevgrad'), ('Burgas', 'Burgas'), ('Varna', 'Varna'), ('Veliko Tarnovo', 'Veliko Tarnovo'), ('Vidin', 'Vidin'), ('Vratsa', 'Vratsa'), ('Gabrovo', 'Gabrovo'), ('Dobrich', 'Dobrich'), ('Kardzhali', 'Kardzhali'), ('Kyustendil', 'Kyustendil'), ('Lovech', 'Lovech'), ('Montana', 'Montana'), ('Pazardzhik', 'Pazardzhik'), ('Pernik', 'Pernik'), ('Pleven', 'Pleven'), ('Plovdiv', 'Plovdiv'), ('Razgrad', 'Razgrad'), ('Ruse', 'Ruse'), ('Shumen', 'Shumen'), ('Silistra', 'Silistra'), ('Sliven', 'Sliven'), ('Smolyan', 'Smolyan'), ('Sofia', 'Sofia'), ('Stara Zagora', 'Stara Zagora'), ('Targovishte', 'Targovishte'), ('Haskovo', 'Haskovo'), ('Yambol', 'Yambol')], max_length=100, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='carpost',
            name='petrol_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=100),
        ),
        migrations.AlterField(
            model_name='carpost',
            name='transmission',
            field=models.CharField(choices=[('Auto', 'Automatic'), ('Manual', 'Manual')], max_length=100),
        ),
    ]
