# Generated by Django 5.0.3 on 2024-03-13 11:31

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpost', '0002_rename_brand_carpost_car_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carfeatures',
            name='exterior_features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('alloy_wheels', 'Alloy Wheels'), ('led_headlights', 'LED Headlights'), ('panoramic_roof', 'Panoramic Roof'), ('power_tailgate', 'Power Tailgate'), ('power_sliding_doors', 'Power Sliding Doors'), ('roof_rails', 'Roof Rails'), ('fog_lights', 'Fog Lights'), ('automatic_headlights', 'Automatic Headlights'), ('rain_sensing_wipers', 'Rain Sensing Wipers'), ('heated_mirrors', 'Heated Mirrors'), ('parking_sensors', 'Parking Sensors'), ('backup_camera', 'Backup Camera')], max_length=100),
        ),
        migrations.AlterField(
            model_name='carfeatures',
            name='interior_features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('leather_seats', 'Leather Seats'), ('navigation_system', 'Navigation System'), ('heated_seats', 'Heated Seats'), ('sunroof', 'Sunroof'), ('power_windows', 'Power Windows'), ('power_seats', 'Power Seats'), ('memory_seats', 'Memory Seats'), ('climate_control', 'Climate Control'), ('premium_audio_system', 'Premium Audio System'), ('wireless_charging', 'Wireless Charging'), ('ambient_lighting', 'Ambient Lighting'), ('rear_entertainment_system', 'Rear Entertainment System')], max_length=100),
        ),
        migrations.AlterField(
            model_name='carfeatures',
            name='safety_features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('abs', 'ABS'), ('airbags', 'Airbags'), ('lane_departure_warning', 'Lane Departure Warning'), ('automatic_emergency_braking', 'Automatic Emergency Braking'), ('blind_spot_monitoring', 'Blind Spot Monitoring'), ('adaptive_cruise_control', 'Adaptive Cruise Control'), ('forward_collision_warning', 'Forward Collision Warning'), ('rear_cross_traffic_alert', 'Rear Cross Traffic Alert'), ('parking_assist', 'Parking Assist'), ('tire_pressure_monitoring', 'Tire Pressure Monitoring'), ('driver_assist_package', 'Driver Assist Package'), ('night_vision_assist', 'Night Vision Assist')], max_length=100),
        ),
    ]
