# Generated by Django 5.0.3 on 2024-03-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpost', '0003_alter_carfeatures_exterior_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carbrands',
            name='logo',
        ),
    ]
