# Generated by Django 5.0.3 on 2024-03-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpost', '0004_remove_carbrands_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(max_length=100),
        ),
    ]
