# Generated by Django 5.0.3 on 2024-03-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpost', '0008_alter_carpost_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carpost',
            name='petrol_type',
        ),
        migrations.AddField(
            model_name='carpost',
            name='horsepower',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
