# Generated by Django 5.0.3 on 2024-04-09 15:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpost', '0016_alter_carmodel_brand_alter_carmodel_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='carposts'),
        ),
    ]
