# Generated by Django 5.0.3 on 2024-04-10 10:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpost', '0017_alter_carpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpost',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='carpost'),
        ),
    ]
