from django.shortcuts import render

# Create your views here.
class RegisterView():
    ...

class LoginView():
    ...
class LogoutView():
    ...

class ProfileDetailsView():
    ...
class ProfileUpdateView():
    ...

class ProfileDeleteView():
    ...